modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="nims_random_bullshit"
version="1.6.0"
displayName="Nim's Random Bullshit"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="nimsolated, MCreator"
description="Random shit added by Nim. Created with MCreator."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.nims_random_bullshit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration